name: Deploy app to S3

on: [ push ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Bucket: ${{ secrets.S3_BUCKET }} ${{ S3_BUCKET }}"

#        - name: Install dependencies
#          run: cd prototyp; yarn
#
#        - name: Build
#          run: cd prototyp; yarn build
#
#        - name: Deploy
#          run: npx s3-deploy ./prototyp/build/** --bucket ${{ secrets.S3_BUCKET }} --region ${{ secrets.S3_BUCKET_REGION }} --cwd ./ --etag --gzip xml,html,htm,js,css,ttf,otf,svg,txt --deleteRemoved --noCache --private
